# Generated by Django 3.2.4 on 2023-10-28 11:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.IntegerField(unique=True)),
                ('amount', models.IntegerField()),
                ('portfolio_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.UUIDField(editable=False)),
                ('amount_traded', models.IntegerField()),
                ('closing_amount', models.IntegerField()),
                ('start_time', models.DateTimeField(null=True)),
                ('closing_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
