# Generated by Django 3.2.4 on 2023-10-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='loss_count_dict',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profit_count_dict',
            field=models.TextField(default='{}'),
        ),
    ]
